# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-sa-cluster

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skywalking-sa-cluster-role
rules:
  - apiGroups: [ "" ]
    resources:
      - "pods" # @feature: cluster; OAP needs to read other OAP Pods information to form a cluster
               # @feature: als; OAP needs to read Pods metadata to analyze the access logs
      - "services" # @feature: als; OAP needs to read services metadata to analyze the access logs
      - "endpoints" # @feature: als; OAP needs to read endpoints metadata to analyze the access logs
      - "nodes" # @feature: als; OAP needs to read nodes metadata to analyze the access logs
      - "configmaps"
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "batch" ]
    resources:
      - "jobs" # @feature: cluster; OAP needs to wait for the init job to complete
    verbs: [ "get", "watch", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skywalking-sa-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skywalking-sa-cluster-role
subjects:
  - kind: ServiceAccount
    name: skywalking-sa-cluster
    namespace: ${NAMESPACE}
