# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
apiVersion: v1
data:
  metadata-service-mapping.yaml: |
    serviceName: mesh-svr::${LABELS."service.istio.io/canonical-name",LABELS."app.kubernetes.io/name",LABELS.app}
    serviceInstanceName: ${NAME,NAME} # Just to skip the "envsubst" replacement
  alarm-settings.yml: |
    rules:
      service_resp_time_rule:
        metrics-name: service_resp_time
        threshold: 20 # 20ms is just for demo
        op: ">"
        period: 5
        count: 1
        message: Response time of service {name} is more than 20ms.
kind: ConfigMap
metadata:
  name: oap-static-config

---
apiVersion: v1
data:
  core.default.log4j-xml: |-
    <Configuration status="WARN">
       <Appenders>
         <Console name="Console" target="SYSTEM_OUT">
           <PatternLayout charset="UTF-8" pattern="%d - %c - %L [%t] %-5p %x - %m%n"/>
         </Console>
       </Appenders>
       <Loggers>
         <logger name="io.grpc.netty" level="INFO"/>
         <logger name="org.apache.skywalking.oap.server.configuration.api" level="TRACE"/>
         <logger name="org.apache.skywalking.oap.server.configuration.configmap" level="DEBUG"/>
         <Root level="INFO">
           <AppenderRef ref="Console"/>
         </Root>
        </Loggers>
    </Configuration>
kind: ConfigMap
metadata:
  labels:
    app: oap
  name: oap-dynamic-config

---
apiVersion: v1
kind: Service
metadata:
  name: oap
spec:
  selector:
    app: oap
  ports:
    - name: metrics
      port: 1234
    - name: grpc
      port: 11800
    - name: http
      port: 12800
    - name: zipkin-receiver
      port: 9411
    - name: zipkin-query
      port: 9412

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oap-deployment
  labels:
    app: oap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oap
  template:
    metadata:
      labels:
        app: oap
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: skywalking-oap-sa # @feature: als; set a service account with Pods/Endpoints/Services/Nodes permissions to analyze Envoy access logs
      containers:
        - name: oap
          image: ${SW_OAP_IMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 4000m
              memory: "4096Mi"
            requests:
              cpu: 1000m
              memory: "1024Mi"
          ports:
            - name: metrics # @feature: so11y; set a name for the metrics port that can be referenced in otel config
              containerPort: 1234
            - name: grpc
              containerPort: 11800
            - name: http
              containerPort: 12800
            - name: zipkin-receiver
              containerPort: 9411
            - name: zipkin-query
              containerPort: 9412
          env:
            - name: SW_CLUSTER_K8S_NAMESPACE
              value: ${NAMESPACE}
            - name: SW_CLUSTER_K8S_LABEL
              value: app=oap
            - name: SW_HEALTH_CHECKER
              value: default
            - name: SW_OTEL_RECEIVER
              value: default # @feature: so11y;mysql;vm;kubernetes-monitor enable OpenTelemetry receiver to receive OpenTelemetry metrics
            - name: SW_OTEL_RECEIVER_ENABLED_OTEL_RULES
              # @feature: vm; enable vm rules to analyze VM metrics
              # @feature: so11y; enable oap rules to analyze OAP metrics
              # @feature: kubernetes-monitor; enable rules to analyze Kubernetes Cluster/Node/Service metrics
              # @feature: istiod-monitor; enable rules to analyze Istio metrics
              # @feature: mysql; enable rules to analyze MySQL metrics
              value: vm,oap,k8s/*,istio-controlplane,mysql/*
            - name: SW_STORAGE
              value: elasticsearch
            - name: SW_STORAGE_ES_CLUSTER_NODES
              value: elasticsearch:9200
            - name: SW_STORAGE_ES_INDEX_REPLICAS_NUMBER
              value: "0"
            - name: SW_TELEMETRY
              value: prometheus # @feature: so11y; expose the metrics of self o11y through prometheus
            - name: SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS
              value: "k8s-mesh,persistence" # @feature: als; enable mesh analyzer (k8s-mesh) to analyze ALS logs
            - name: K8S_SERVICE_NAME_RULE
              value: "mesh-svr::${service.metadata.name}"
            - name: SW_CONFIGURATION
              value: k8s-configmap
            - name: SW_ENABLE_ON_DEMAND_POD_LOG
              value: "true"
            - name: SW_METER_ANALYZER_ACTIVE_FILES
              value: datasource,threadpool,satellite,network-profiling,spring-sleuth
            - name: SW_STORAGE_ES_RESPONSE_TIMEOUT
              value: "50000"
            - name: SW_RECEIVER_ZIPKIN
              value: default
            - name: SW_QUERY_ZIPKIN
              value: default
          volumeMounts:
            - name: config-volume
              mountPath: /skywalking/ext-config
      volumes:
        - name: config-volume
          configMap:
            name: oap-static-config

---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: ui
          image: ${SW_UI_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 10
          env:
            - name: SW_OAP_ADDRESS
              value: http://oap:12800
            - name: SW_ZIPKIN_ADDRESS
              value: http://oap:9412
